Task 4 dev
Coding-Seal/yadro-go-course pull request #10
Opened 2024-04-22 11:24 UTC by Coding-Seal

Общие изменения
---  
- Переписал забор комиксов с мапы с семафором на workerPool и передаю комиксы между горутинами через каналы (удобно для получения по одному)
- Теперь использую json lines => дописываю недостающие комиксы в конец файла, а не переписываю весь файл
-  Решил хранить больше информации про комиксы для удобства
---
Задание 4  #8
---
- Строить индекс очень быстро => не буду сохранять в файл, строю каждый раз
- Использовать индекс на порядок быстрее, просто бегать по мапе

2024-04-23 07:31 UTC, vbelogrudov requested changes
Привет!

make test и bench пока не работают.
С поиском тоже пока не все гладко -
➜  Coding-Seal/yadro-go-course git:(Task-4-dev) ✗ ./xkcd -c config.yaml -i -s "binary christmas tree"
2024/04/23 10:28:07 loading comics from db
2024/04/23 10:28:07 downloading remaining comics
2024/04/23 10:28:07 saving comics in DB
2024/04/23 10:28:07 Done

хочется найти https://xkcd.com/835 

У тебя есть map foundComics, можно сделать ранжирование комиксов, чтобы показывать, например, комиксы с половиной найденных слов или вообще одним

2024-04-23 07:31 UTC, vbelogrudov commented on cmd/xkcd/main.go
> +	searchPhrase = "I'm following your questions"
это, наверное, забыл убрать ;)

2024-04-23 18:34 UTC, Coding-Seal commented
Я решил попробовать ранжировать комиксы как-нибудь поинтереснее (учитывать частоту слов в поисковой фразе и количество слов в комиксе)

2024-04-24 09:13 UTC, vbelogrudov approved these changes
привет!

что-то находится, но поиск все еще можно улучшить в будущем, например:
```

➜  Coding-Seal/yadro-go-course git:(Task-4-dev) ✗ ./xkcd -c config.yaml -i -s 'an apple a day keeps doctors away'
2024/04/24 12:11:27 loading comics from db
2024/04/24 12:11:27 downloading remaining comics
2024/04/24 12:11:27 remaining comics fetched failed: LastID : Get "https://xkcd.com/info.0.json": read tcp 172.22.2.85:47524->151.101.0.67:443: read: connection reset by peer
2024/04/24 12:11:27 saving comics in DB
2024/04/24 12:11:27 Birth https://imgs.xkcd.com/comics/birth.png score: 3
2024/04/24 12:11:27 Bracket https://imgs.xkcd.com/comics/bracket.png score: 3
2024/04/24 12:11:27 Delivery https://imgs.xkcd.com/comics/delivery.png score: 3
2024/04/24 12:11:27 Fixion https://imgs.xkcd.com/comics/fixion.png score: 3
2024/04/24 12:11:27 Frankenstein https://imgs.xkcd.com/comics/frankenstein.png score: 3
2024/04/24 12:11:27 Gut Fauna https://imgs.xkcd.com/comics/gut_fauna.png score: 3
2024/04/24 12:11:27 Incision https://imgs.xkcd.com/comics/incision.png score: 3
2024/04/24 12:11:27 Keynote https://imgs.xkcd.com/comics/keynote.png score: 3
2024/04/24 12:11:27 Pain Rating https://imgs.xkcd.com/comics/pain_rating.png score: 3
2024/04/24 12:11:27 T-Cells https://imgs.xkcd.com/comics/t_cells.png score: 3
2024/04/24 12:11:27 Done
```
https://xkcd.com/2161 ->  https://imgs.xkcd.com/comics/an_apple_a_day.png

2024-04-24 09:13 UTC, vbelogrudov commented on internal/app/app_test.go
> +	client.SearchComics(phrase)
здесь стоит добавить for i := 0; i < b.N; i++ , чтобы была более правильная статистика

2024-04-24 09:13 UTC, vbelogrudov commented on internal/app/app_test.go
> +	client.SearchIndex(phrase)
здесь стоит добавить for i := 0; i < b.N; i++ , чтобы была более правильная статистика

2024-04-29 17:08 UTC, merged